//
// Created by Andrew Graser on 2/28/2024.
//

#ifndef SANDBOX_MOUSEBUTTONCODES_H
#define SANDBOX_MOUSEBUTTONCODES_H

namespace Tungsten {
#define TUNGSTEN_MOUSE_BUTTON_1         0
#define TUNGSTEN_MOUSE_BUTTON_2         1
#define TUNGSTEN_MOUSE_BUTTON_3         2
#define TUNGSTEN_MOUSE_BUTTON_4         3
#define TUNGSTEN_MOUSE_BUTTON_5         4
#define TUNGSTEN_MOUSE_BUTTON_6         5
#define TUNGSTEN_MOUSE_BUTTON_7         6
#define TUNGSTEN_MOUSE_BUTTON_8         7
#define TUNGSTEN_MOUSE_BUTTON_LAST      TUNGSTEN_MOUSE_BUTTON_8
#define TUNGSTEN_MOUSE_BUTTON_LEFT      TUNGSTEN_MOUSE_BUTTON_1
#define TUNGSTEN_MOUSE_BUTTON_RIGHT     TUNGSTEN_MOUSE_BUTTON_2
#define TUNGSTEN_MOUSE_BUTTON_MIDDLE    TUNGSTEN_MOUSE_BUTTON_3
}

#endif //SANDBOX_MOUSEBUTTONCODES_H
